name: akshay-github-action-ci

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.9.22]

    steps:
    - uses: actions/checkout@v3
    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    

    - name: install dependency
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: run test
      run: |
        cd src
        python -m pytest addition.py


