name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --upgrade pip
        cd python_container_app
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        cd python_container_app
        python -m pytest app.py
    - name: run build
      run: |
        cd python_container_app
        python3 app.py
